name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # 根据项目需求调整 Node.js 版本

    # 安装依赖
    - name: Install dependencies
      run: npm install

    # 构建项目
    - name: Build project
      run: npm run docs:build

    # 同步构建结果到目标服务器
    - name: Sync build to server
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          .vitepress/dist/ \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}