# deploy.yml
name: 部署到服务器
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2
      # 使用 node:22
      - name: use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: 22
      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      # build
      - name: vitepress build
        run: |
          npm run docs:build
        env:
          CI: true

      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: ".vitepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}